### ISSUE TITLE
IndexError due to changing "reward" to "round_reward"

### ISSUE THREAD

**Issue by GMMDMDIDEMS** [pyrddlgym-project/pyRDDLGym-prost#3]
With the PR https://github.com/pyrddlgym-project/pyRDDLGym/pull/240 I introduced an IndexError in https://github.com/pyrddlgym-project/pyRDDLGym-prost/blob/999e0ee6e6bc9e512f65839cc53ce63c5b264fc8/prost/rddlsim.py#L28

## Fix
- change "reward" to "round_reward"

**Comment by mike-gimelfarb** [comment]
Thanks for the fix. Looks like I will need to do testing to make sure all the v2 changes are carried.

**Comment by mike-gimelfarb** [comment]
Thanks for the fix. Looks like everything is running now.
